# Generated by Django 6.0.6 on 2026-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
