# Generated by Django 6.0.6 on 2026-08-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_category_created_at_alter_foods_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='restaurant.category'),
        ),
    ]
