# Generated by Django 6.0.6 on 2026-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_foods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='تصویر غذا'),
        ),
    ]
