# Generated by Django 6.0.6 on 2026-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='calculated_avg',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
